# Generated by Django 5.1 on 2024-08-23 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(blank=True, max_length=100)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
